export const Positions = [
    {
       "x":136,
       "y":-761,
       "z":45,
       "height":5,
       "range":2,
       "name":"FBI",
       "stage":1
    },
    {
       "x":136,
       "y":-761,
       "z":242,
       "height":5,
       "range":2,
       "name":"FBI",
       "stage":49
    },
    {
      "x":136,
      "y":-761,
      "z":242,
      "height":5,
      "range":2,
      "name":"FBI1",
      "stage":49
   }
 ]